name: ROS TEST

on: [push, pull_request]
jobs:
  test_on_container:
    runs-on: ubuntu-latest
    container: ros:melodic
    env:
      ROS_DISTRO: melodic
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          DIRNAME=$(basename ${GITHUB_REPOSITORY})
          echo $DIRNAME
          apt-get update
          apt-get install -y python python-pip python-dev python-gdbm python-tk
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin_make
          cd ~/catkin_ws/src
          ln -s /__w/$DIRNAME/$DIRNAME .
          cd $DIRNAME
          pip install wheel
          pip install -r requirements.txt
      - name: Tests
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          source ~/catkin_ws/devel/setup.bash
          cd ~/catkin_ws
          catkin_make run_tests
      - name: Verify
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          source ~/catkin_ws/devel/setup.bash
          cd ~/catkin_ws
          catkin_make test
